version: "3.8"
services: 
    webapp:
        build:
            context: .
            dockerfile: ./dockerfile
        ports:
            - "8001:80"
        volumes:
            - ./src:var/www
        environment: 
            - UNSPLASH_ACCESS_KEY=22bc8e1f93fc4cc12ed3428f2e41ffe4f193dada12c414721811658012cc24b4
            - UNSPLASH_SECRET_KEY=1e61323d10a0ccdf955744e25d2b73fe4c10dc63a5a2597bb9103da614c7a36c